"""make image_url nullable for video ads

Revision ID: 4d4e06ff4640
Revises: e9173c698de9
Create Date: 2025-12-03 18:40:05.412330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4e06ff4640'
down_revision: Union[str, Sequence[str], None] = 'e9173c698de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_ads', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_ads', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
