"""Add page blacklist

Revision ID: 4ee5013722ea
Revises: 6e99aaf7477f
Create Date: 2025-12-06 16:37:33.364354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee5013722ea'
down_revision: Union[str, Sequence[str], None] = '6e99aaf7477f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_blacklist_page_name'), 'page_blacklist', ['page_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_blacklist_page_name'), table_name='page_blacklist')
    op.drop_table('page_blacklist')
    # ### end Alembic commands ###
