"""Add API usage tracking

Revision ID: 6e99aaf7477f
Revises: 63461f58bb98
Create Date: 2025-12-06 16:32:44.236219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e99aaf7477f'
down_revision: Union[str, Sequence[str], None] = '63461f58bb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('api_calls', sa.Integer(), nullable=False),
    sa.Column('ads_returned', sa.Integer(), nullable=False),
    sa.Column('ads_saved', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_date'), 'api_usage_logs', ['date'], unique=False)
    op.drop_constraint(op.f('uq_scraped_ads_external_id'), 'scraped_ads', type_='unique')
    op.drop_index(op.f('ix_scraped_ads_external_id'), table_name='scraped_ads')
    op.create_index(op.f('ix_scraped_ads_external_id'), 'scraped_ads', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_ads_external_id'), table_name='scraped_ads')
    op.create_index(op.f('ix_scraped_ads_external_id'), 'scraped_ads', ['external_id'], unique=False)
    op.create_unique_constraint(op.f('uq_scraped_ads_external_id'), 'scraped_ads', ['external_id'])
    op.drop_index(op.f('ix_api_usage_logs_date'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
