"""Add keyword blacklist

Revision ID: c2e11c6fd885
Revises: 4ee5013722ea
Create Date: 2025-12-06 16:52:40.917433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e11c6fd885'
down_revision: Union[str, Sequence[str], None] = '4ee5013722ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_blacklist_keyword'), 'keyword_blacklist', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_blacklist_keyword'), table_name='keyword_blacklist')
    op.drop_table('keyword_blacklist')
    # ### end Alembic commands ###
